services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    hostname: "gitlab.verulam.dev"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://dev.verulam.ru/'
    volumes:
      - "${GITLAB_HOME}/config:/etc/gitlab"
      - "${GITLAB_HOME}/logs:/var/log/gitlab"
      - "${GITLAB_HOME}/data:/var/opt/gitlab"
    expose:
      - "80"
      - "443"
      - "22"
    shm_size: "256m"
    networks:
      - gitlab_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2222:2222"
    volumes:
      - "${NGINX_CONF}:/etc/nginx/nginx.conf"
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - gitlab_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email lenyaplay@mail.ru -d "dev.verulam.ru" --agree-tos
    depends_on:
      - nginx
    networks:
      - gitlab_network

networks:
  gitlab_network:
    driver: bridge
